//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santa_luchia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public int ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> ТипТовара { get; set; }
        public Nullable<int> НоменклНомер { get; set; }
        public string КолНаСкладе { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<decimal> ЗакупЦенаШт { get; set; }
        public Nullable<decimal> НаценкаКомпании { get; set; }
        public Nullable<int> Поставщик { get; set; }
        public Nullable<int> Фото { get; set; }
        public Nullable<int> Склад { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        public virtual Склады Склады { get; set; }
        public virtual Тип Тип { get; set; }
        public virtual Фотодж Фотодж { get; set; }
    }
}
